# Automate deployment of containers

name: Deploy Workflow
on: 
    workflow_dispatch
# on: 
#     push:
#         branches:
#             - 'main'

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: ella-adeka/frontend
                      dockerfile: qr-code-generator/front-end-nextjs/Dockerfile
                    - image: ella-adeka/api
                      dockerfile: qr-code-generator/api/Dockerfile
        permissions:
            id-token: write
            contents: read
            actions: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Automate deployment of containers
              run: echo "Automating deployment of containers"

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ env.DOCKERHUB_USERNAME }}
                password: ${{ env.DOCKERHUB_TOKEN }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ matrix.image }}
        
            - name: Build and Push Application
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ${{ matrix.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha, mode=max

    deploy:
        name: Deploy
        needs: [ build ]
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            actions: read
            packages: write
        steps:
            - name: Setup Kubernetes Context
              uses: azure/k8s-set-context@v2
              with: 
                method: service-account
                k8s-url: <server-url>
                k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy to Kubernetes
              uses: azure/k8s-deploy@v1
              with:
                namespace: default
                manifests: |
                    kubernetes/frontend/frontend-deployment.yaml
                    kubernetes/frontend/frontend-service.yaml
                    kubernetes/api/api-deployment.yaml
                    kubernetes/api/api-service.yaml
                    
            #   run: |
            #     kubectl apply -f kubernetes/nextjs/nextjs-deployment.yaml
            #     kubectl apply -f kubernetes/nextjs/nextjs-service.yaml
              
            #     kubectl apply -f kubernetes/fastapi/fastapi-deployment.yaml
            #     kubectl apply -f kubernetes/fastapi/fastapi-service.yaml
              