# Test entire application

name: Test Application
on: 
    workflow_dispatch
# on: 
#     push:
#         branches:
#             - 'main'

jobs:
    test-frontend:
        name: test-frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run frontend test
              run: echo "Testing frontend"

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            
            - name: Install npm
              working-directory: ./front-end-nextjs
              run: npm install
              
            - name: Run frontend test
              working-directory: ./front-end-nextjs
              run: npm test

    test-backend:
        name: test-backend
        needs: [ test-frontend ]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Run backend test
              run: echo "Testing backend"

            - name: Set up Python
              uses: actions/setup-python@v3
              with: 
                python-version: '3.9'

            - name: Install dependencies
              working-directory: ./api
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Test with pytest
              working-directory: ./api
              run: pytest test.py


    